    name: Django CI/CD

    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - main

    jobs:
      quality_assurance:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.9' # or your project's Python version
          - name: Install Poetry
            uses: snok/install-poetry@v1
          - name: Install dependencies
            run: poetry install --no-root
          - name: Run tests
            run: poetry run python manage.py test
     


   
